# Fix corrupted settings.json - simpler version
$settingsPath = "c:\Users\seand\AppData\Roaming\Code\User\settings.json"
$content = Get-Content $settingsPath -Raw

# Find the start of allowedCommands
$startIdx = $content.IndexOf('"kilo-code.allowedCommands": [')
if ($startIdx -lt 0) {
    Write-Host "Could not find allowedCommands"
    exit 1
}

# Find the end of allowedCommands 
$endIdx = $content.IndexOf('],', $startIdx) + 2
if ($endIdx -lt 2) {
    Write-Host "Could not find end of allowedCommands"
    exit 1
}

# Get the parts before and after
$before = $content.Substring(0, $startIdx)
$after = $content.Substring($endIdx)

# Build commands string manually
$commands = @"
    "git",
    "git log",
    "git diff",
    "git show",
    "git status",
    "git add",
    "git commit",
    "git push",
    "git pull",
    "git branch",
    "git checkout",
    "git fetch",
    "git merge",
    "git rebase",
    "git stash",
    "git reset",
    "git clean",
    "node",
    "npm",
    "npx",
    "yarn",
    "pnpm",
    "bun",
    "deno",
    "powershell",
    "pwsh",
    "cmd",
    "curl",
    "wget",
    "python",
    "python3",
    "pip",
    "pip3",
    "docker",
    "docker-compose",
    "kubectl",
    "helm",
    "terraform",
    "ansible",
    "bash",
    "sh",
    "chmod",
    "mkdir",
    "rm",
    "cp",
    "mv",
    "touch",
    "cat",
    "echo",
    "grep",
    "find",
    "tar",
    "zip",
    "unzip",
    "ssh",
    "scp",
    "rsync",
    "ping",
    "netstat",
    "nslookup",
    "whoami",
    "pwd",
    "dir",
    "cd",
    "type",
    "ls",
    "tasklist",
    "taskkill",
    "netstat -ano",
    "ipconfig",
    "Get-Process",
    "Start-Process",
    "Stop-Process",
    "Test-NetConnection",
    "Invoke-WebRequest",
    "Invoke-RestMethod",
    "Get-Content",
    "Set-Content",
    "Remove-Item",
    "Copy-Item",
    "Move-Item",
    "New-Item",
    "Get-ChildItem",
    "npm install",
    "npm run",
    "npm start",
    "npm test",
    "npm build",
    "npm run dev",
    "yarn install",
    "yarn run",
    "pnpm install",
    "pip install",
    "docker build",
    "docker run",
    "docker ps",
    "docker stop",
    "kubectl get pods",
    "kubectl apply",
    "kubectl delete",
    "curl -s",
    "curl -X",
    "curl -H",
    "curl -d",
    "curl http://localhost",
    "curl https://localhost",
    "node -e",
    "node -p",
    "python -m",
    "make",
    "cmake",
    "gradle",
    "maven",
    "cargo",
    "rustc",
    "go",
    "gcc",
    "g++",
    "javac",
    "java",
    "psql",
    "mysql",
    "sqlite3",
    "mongosh",
    "redis-cli",
    "npm config",
    "npm --version",
    "node --version",
    "docker --version",
    "git --version",
    "curl --version",
    "bash --version",
    "npm login",
    "npm publish",
    "git push -u",
    "git push --force",
    "git pull --rebase",
    "ls -la",
    "ls -l",
    "dir /a",
    "Get-ChildItem -Force",
    "Test-Path",
    "Split-Path",
    "NODE_OPTIONS",
    "NODE_ENV",
    "PORT",
    "HOST",
    "docker build -t",
    "docker run -d",
    "docker run -p",
    "kubectl run",
    "kubectl expose",
    "kubectl exec -it",
    "terraform init",
    "terraform plan",
    "terraform apply",
    "ansible-playbook",
    "helm install",
    "helm upgrade",
    "jest",
    "vitest",
    "mocha",
    "pytest",
    "cypress run",
    "cypress open",
    "playwright test"
"@

$newSection = "`"kilo-code.allowedCommands`: [
  $commands
  ]"

# Combine
$newContent = $before + $newSection + $after

# Write
Set-Content -Path $settingsPath -Value $newContent -NoNewline

Write-Host "Settings.json fixed!"
